# Generated by Django 4.1 on 2022-09-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUdiko', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
