# Generated by Django 4.1 on 2022-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUdiko', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='aubook/images'),
        ),
    ]
