# Generated by Django 4.1 on 2022-09-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUdiko', '0003_book_genre_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
    ]
